name: smooth_gradient
description: "A new Flutter package project."
version: 0.0.1
homepage: "https://nikodembernat.com"
repository: "https://github.com/n-bernat/flutter_smooth_gradient"
issue_tracker: "https://github.com/n-bernat/flutter_smooth_gradient/issues"
topics:
  - flutter
  - gradient
  - smooth
  - ui

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^14.1.0
