name: smooth_gradient
description: "A package that allows you to create gradients that use a specific curve."
version: 0.1.0
homepage: "https://nikodembernat.com"
repository: "https://github.com/n-bernat/flutter_smooth_gradient"
issue_tracker: "https://github.com/n-bernat/flutter_smooth_gradient/issues"
screenshots:
  - description: Preview of various curves
    path: screenshots/screenshot.png
topics:
  - flutter
  - gradient
  - smooth
  - ui

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^14.1.0
